#!/usr/bin/env bash
set -e

FROM=`date +%FT00:00:00%z`
TO=`date +%FT00:00:00%z -d tomorrow`
HOSTNAME="github.com"

while [ $# -gt 0 ]; do
  case "$1" in
    --hostname)
      HOSTNAME="$2"
      shift
      ;;
    --from)
      FROM="$2"
      shift
      ;;
    --to)
      TO="$2"
      shift
      ;;
  esac
  shift
done

JQ_QUERY="
[
  .[] |
  select((.created_at >= \"$FROM\") and (.created_at <= \"$TO\") and (.type | startswith(\"Pull\") or startswith(\"Issue\"))) |
  {\"type\": .type, \"repo\": .repo.name, \"title\": (.payload.pull_request // .payload.issue).title, \"url\": (.payload.review // .payload.comment // .payload.pull_request // .payload.issue).html_url}
] | 
group_by(.repo) |
map({repo: .[0].repo, activities: .}) |
map(\"\n### \" + .repo +\"\n\", (.activities | group_by(.type, .url)[] | flatten | unique | map(\"- [\" + .type[0:-5] + \"](\" + .url + \"): \" + .title))) |
flatten |
.[]"

USER=$(gh api user -q .login --hostname "$HOSTNAME")

exec gh api users/kenchan/events --hostname "$HOSTNAME" --paginate -q "$JQ_QUERY"
