#!/usr/bin/env bash
set -e

FROM=`date +%FT00:00:00%z`
TO=`date +%FT00:00:00%z -d tomorrow`

JQ_QUERY="
[
  .[] |
  select((.created_at >= \"$FROM\") and (.created_at <= \"$TO\") and (.type | startswith(\"Pull\") or startswith(\"Issue\"))) |
  {\"type\": .type, \"repo\": .repo.name, \"title\": (.payload.pull_request // .payload.issue).title, \"url\": (.payload.review // .payload.comment // .payload.pull_request // .payload.issue).html_url}
] |
group_by(.type, .url) |
flatten |
unique |
map(\"- \" + .repo + \": [\" + .type[0:-5] + \"](\" + .url + \") \" + .title) |
.[]"

USER=$(gh api user -q .login "$@")

exec gh api users/kenchan/events "$@" --paginate -q "$JQ_QUERY"
